
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxidma.h"

/*
* The configuration table for devices
*/

XAxiDma_Config XAxiDma_ConfigTable[] =
{
	{
		XPAR_ETH_A_DMA_DEVICE_ID,
		XPAR_ETH_A_DMA_BASEADDR,
		XPAR_ETH_A_DMA_SG_INCLUDE_STSCNTRL_STRM,
		XPAR_ETH_A_DMA_INCLUDE_MM2S,
		XPAR_ETH_A_DMA_INCLUDE_MM2S_DRE,
		XPAR_ETH_A_DMA_M_AXIS_MM2S_TDATA_WIDTH,
		XPAR_ETH_A_DMA_INCLUDE_S2MM,
		XPAR_ETH_A_DMA_INCLUDE_S2MM_DRE,
		XPAR_ETH_A_DMA_S_AXIS_S2MM_TDATA_WIDTH,
		XPAR_ETH_A_DMA_INCLUDE_SG,
		XPAR_ETH_A_DMA_NUM_MM2S_CHANNELS,
		XPAR_ETH_A_DMA_NUM_S2MM_CHANNELS
	},
	{
		XPAR_ETH_B_DMA_DEVICE_ID,
		XPAR_ETH_B_DMA_BASEADDR,
		XPAR_ETH_B_DMA_SG_INCLUDE_STSCNTRL_STRM,
		XPAR_ETH_B_DMA_INCLUDE_MM2S,
		XPAR_ETH_B_DMA_INCLUDE_MM2S_DRE,
		XPAR_ETH_B_DMA_M_AXIS_MM2S_TDATA_WIDTH,
		XPAR_ETH_B_DMA_INCLUDE_S2MM,
		XPAR_ETH_B_DMA_INCLUDE_S2MM_DRE,
		XPAR_ETH_B_DMA_S_AXIS_S2MM_TDATA_WIDTH,
		XPAR_ETH_B_DMA_INCLUDE_SG,
		XPAR_ETH_B_DMA_NUM_MM2S_CHANNELS,
		XPAR_ETH_B_DMA_NUM_S2MM_CHANNELS
	}
};


