
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.4 EDK_P.49d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsysmon.h"

/*
* The configuration table for devices
*/

XSysMon_Config XSysMon_ConfigTable[] =
{
	{
		XPAR_AXI_SYSMON_DEVICE_ID,
		XPAR_AXI_SYSMON_BASEADDR,
		XPAR_AXI_SYSMON_INCLUDE_INTR
	}
};


